-- Bluetooth A2DP device overrides.
-- Generated by bin/setup-bt-a2dp-fix from dot_config/bt-a2dp-fix/config.

local card = "bluez_card.84_AC_60_30_CF_32"

-- Keep a2dp_source for stable negotiation on some headsets; auto-connect playback only.
bluez_monitor.properties = {
  ["bluez5.roles"] = "[ a2dp_sink a2dp_source hfp_hf ]",
}

bluez_monitor.rules = {
  {
    matches = {
      {
        { "device.name", "matches", card },
      },
    },
    apply_properties = {
      ["bluez5.auto-connect"] = "[ a2dp_sink ]",
    },
  },
}
